apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-yfyh
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0075-tenant/tkrw-pr712-0075-0075-app/devfile-sample-yfyh@sha256:904d24db07f44ee0d70273896e3a4a336afd96de44ebcc09225523b5f8427cfe
        name: my-nodejs
        resources: {}
status: {}
